
@@ -0,0 +1,22 @@
input {
  file {
    pathh => "/caminho/para/seu/arquivo.log"
    type => "log"
  }
}

filter { 
  grok {
    match => { "message" => "%{IP:ip} %{WORD:metodo} %{NUMBER:status}" }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
  }
}
